### ISSUE TITLE
Volume not changing for games Win 11

### ISSUE THREAD

**Issue by JedaCheese** [omriharel/deej#134]
I am having issues with changing the volume for any games that are running. Discord, Chrome and Main volume adjust perfectly. I never had this issue on my Windows 10 PC (I've just built a new PC and it has Win 11)

Config file is as follows:
```
# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions) (experimental)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not) (experimental)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: 
    - bg3.exe
    - bg3_dx11.exe
    - factorio.exe
    - Medieval_Dynasty.exe
    - Ranch_Simulator.exe
    - WalkingSim.exe
  2: discord.exe
  3: chrome.exe
  4: spotify.exe

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM3
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default

```
